version: '3.1'

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - .data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080